name: Deploy no GitHub Pages

on:
  push:
    branches:
      - main  # ou 'master', dependendo da sua branch principal

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Pegar os arquivos do repositório
        uses: actions/checkout@v3

      - name: Deploy no GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: src  # 👈 Aqui apontando pra sua pasta com o site
